### ISSUE TITLE
求添加边缘阴影效果

### ISSUE THREAD

**Issue by Matrix6677** [BlueMor/DragLayout#1]
RT。。。。。。

**Comment by 275288698** [comment]
i think you can do it self

**Comment by BlueMor** [comment]
已加

**Comment by Matrix6677** [comment]
这么快！！我更新看看帅不帅~

**Comment by Matrix6677** [comment]
我想要实现类似 [AndroidResideMenu](https://github.com/SpecialCyCi/AndroidResideMenu) 这样的边缘阴影效果；还有就是在菜单栏里面点击打开的Activity可不可以直接替换掉MainActivity里的布局，统一动画效果，亦如AndroidResideMenu那样，thanks~

**Comment by BlueMor** [comment]
阴影大小可自己找到相关参数修改；在MyRelativeLayout中add/replace fragment就行了
